[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.env]
NIXPACKS_PYTHON_VERSION = "3.10"

# Railway 将注入 $PORT 环境变量
# 应用会从 os.getenv("PORT", 8889) 读取端口
